export const SOCKET_EVENTS = {
  APPLICATION_STATUS_UPDATED: "APPLICATION_STATUS_UPDATED",
  NEW_APPLICATION: "NEW_APPLICATION",
  NEW_JOB: "NEW_JOB",
  OFFER_ACCEPTED: "OFFER_ACCEPTED",
  SYSTEM_ALERT: "SYSTEM_ALERT",
} as const;
